import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    background: {
        flex: 1,
    },
    fixedHeader: {
        alignItems: "center",
        paddingVertical: screenHeight * 0.025,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginBottom: screenHeight * 0.012,
    },
    backButton: {
        position: "absolute",
        top: screenHeight * 0.09,
        left: screenWidth * 0.06,
        zIndex: 10,
    },
    backIcon: {
        fontSize: Math.min(screenWidth * 0.12, 48),
        color: "#000",
        fontWeight: "200",
    },
    headerText: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: "bold",
        color: "#333",
    },
    scrollableContent: {
        flex: 1,
        marginTop: screenHeight * 0.065,
        marginBottom: screenHeight * 0.010,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingBottom: screenHeight * 0.020,
    },
    inputContainer: {
        marginHorizontal: screenWidth * 0.05,
        padding: screenWidth * 0.05,
        backgroundColor: "#FFF",
        borderRadius: 10,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    label: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#333",
        marginBottom: screenHeight * 0.012,
    },
    input: {
        height: screenHeight * 0.065,
        backgroundColor: "#F7F7F7",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        marginBottom: screenHeight * 0.025,
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#333",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    dateInput: {
        height: screenHeight * 0.065,
        backgroundColor: "#F7F7F7",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        justifyContent: "center",
        marginBottom: screenHeight * 0.025,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    dateText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#333",
    },
    textArea: {
        height: screenHeight * 0.13,
        backgroundColor: "#F7F7F7",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        paddingVertical: screenHeight * 0.012,
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#333",
        textAlignVertical: "top",
    },
    saveButton: {
        paddingVertical: screenHeight * 0.02,
        borderRadius: 10,
        backgroundColor: "#4CAF50",
        alignItems: "center",
        marginTop: screenHeight * 0.025,
    },
    saveButtonText: {
        fontSize: Math.min(screenWidth * 0.045, 18),
        fontWeight: "bold",
        color: "#FFF",
    },
    dropdownContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        marginBottom: screenHeight * 0.025,
    },
    dropdownItem: {
        width: "48%",
        paddingVertical: screenHeight * 0.012,
        borderWidth: 2,
        borderColor: "#FFD700",
        borderRadius: 5,
        alignItems: "center",
        marginBottom: screenHeight * 0.012,
    },
    dropdownItemSelected: {
        backgroundColor: "#FFD700",
    },
    dropdownText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#FFD700",
    },
    dropdownTextSelected: {
        color: "#FFF",
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
        borderRadius: 10,
    },
    loadingContainer: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 15,
        alignItems: 'center',
        minWidth: 200,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth: 2,
        borderColor: '#3B82F6',
    },
    loadingText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 10,
    },
});