import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    background: {
        flex: 1,
    },
    backButton: {
        position: "absolute",
        top: screenHeight * 0.09,
        left: screenWidth * 0.06,
        zIndex: 10,
    },
    backIcon: {
        fontSize: Math.min(screenWidth * 0.12, 48),
        color: "#000",
        fontWeight: "200",
    },
    header: {
        alignItems: "center",
        paddingVertical: screenHeight * 0.025,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginBottom: screenHeight * 0.025,
    },
    headerText: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: "bold",
        color: "#333",
    },
    searchContainer: {
        paddingHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
        marginTop: screenHeight * 0.040,
    },
    searchInput: {
        height: screenHeight * 0.065,
        backgroundColor: "#FFF",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        fontSize: Math.min(screenWidth * 0.04, 16),
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        color: "#333",
    },
    scrollableList: {
        flex: 1,
        marginHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
        borderRadius: 10,
        overflow: "hidden",
    },
    eventCard: {
        backgroundColor: "#FFF",
        borderRadius: 10,
        padding: screenWidth * 0.035,
        marginBottom: screenHeight * 0.018,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    eventName: {
        fontSize: Math.min(screenWidth * 0.045, 18),
        fontWeight: "bold",
        color: "#333",
        marginBottom: screenHeight * 0.008,
    },
    eventDate: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#690",
        fontWeight: "bold",
        marginBottom: screenHeight * 0.004,
    },
    eventTime: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#690",
        fontWeight: "bold",
        marginBottom: screenHeight * 0.002,
    },

    emptyText: {
        textAlign: "center",
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#999",
        marginTop: screenHeight * 0.02,
    },
    datePickerButton: {
        width: "88%",
        backgroundColor: "#FFD700",
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 8,
        shadowColor: "transparent",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
        alignItems: "center",
        alignSelf: "center",
        marginTop: screenHeight * 0.060,
        marginBottom: 0,
    },
    datePickerText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#000",
        fontWeight: "bold",
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingContainer: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    loadingText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 10,
    },
});
