import { StyleSheet, Dimensions, Platform } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    background: {
        flex: 1,
    },
    backButton: {
        position: "absolute",
        top: screenHeight * 0.09,
        left: screenWidth * 0.06,
        zIndex: 10,
    },
    backIcon: {
        fontSize: Math.min(screenWidth * 0.12, 48),
        color: "#000",
        fontWeight: "200",
    },
    header: {
        alignItems: "center",
        paddingVertical: screenHeight * 0.025,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginBottom: screenHeight * 0.012,
    },
    headerText: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: "bold",
        color: "#333",
    },
    searchContainer: {
        paddingHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.012,
        marginTop: screenHeight * 0.037,
    },
    searchInput: {
        height: screenHeight * 0.065,
        backgroundColor: "#FFF",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        fontSize: Math.min(screenWidth * 0.04, 16),
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        color: "#333",
    },
    scrollableList: {
        height: "44%",
        width: "90%",
        marginHorizontal: "5%",
        marginBottom: screenHeight * 0.025,
        paddingVertical: screenHeight * 0.012,
        borderRadius: 10,
        borderWidth: 0,
        overflow: "hidden",
    },
    eventCard: {
        backgroundColor: "#FFF",
        borderRadius: 10,
        padding: screenWidth * 0.04,
        marginBottom: screenHeight * 0.018,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    eventDetails: {
        flex: 1,
    },
    eventName: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#333",
    },
    eventDate: {
        fontSize: Math.min(screenWidth * 0.035, 14),
        color: "#666",
    },
    eventActions: {
        flexDirection: "row",
        alignItems: "center",
    },
    editButton: {
        backgroundColor: "#FFD700",
        paddingVertical: screenHeight * 0.006,
        paddingHorizontal: screenWidth * 0.025,
        borderRadius: 5,
        marginRight: screenWidth * 0.025,
    },
    deleteButton: {
        backgroundColor: "#FF5733",
        paddingVertical: screenHeight * 0.006,
        paddingHorizontal: screenWidth * 0.025,
        borderRadius: 5,
    },
    buttonText: {
        fontSize: Math.min(screenWidth * 0.035, 14),
        color: "#FFF",
        fontWeight: "bold",
    },
    addButtonContainer: {
        width: '100%',
        alignItems: "center",
        marginTop: screenHeight * 0.02,
        marginBottom: Platform.OS === 'ios' ? screenHeight * 0.04 : screenHeight * 0.03,
        paddingHorizontal: screenWidth * 0.05,
    },
    addButton: {
        backgroundColor: "#4CAF50",
        paddingVertical: screenHeight * 0.02,
        borderRadius: 10,
        alignItems: "center",
        width: "90%",
    },
    addButtonText: {
        color: "#FFF",
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
    },
    tabContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 0,
        marginTop: screenHeight * 0.075,
        marginHorizontal: screenWidth * 0.05,
    },
    tabButton: {
        flex: 1,
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderWidth: 2,
        borderColor: "#FFD700",
        borderRadius: 10,
        alignItems: "center",
        marginHorizontal: screenWidth * 0.012,
    },
    tabButtonActive1: {
        backgroundColor: "#4CAF50",
    },
    tabButtonActive2: {
        backgroundColor: "#FF5733",
    },
    tabButtonText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#FFD700",
    },
    tabButtonTextActive: {
        color: "#FFF",
    },
    listSafeArea: {
        maxHeight: screenHeight * 0.6,
        width: "90%",
        alignSelf: "center",
        backgroundColor: "#FFF",
        borderRadius: 10,
        paddingVertical: screenHeight * 0.012,
        marginTop: screenHeight * 0.012,
        marginBottom: screenHeight * 0.025,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingBottom: Platform.OS === 'ios' ? screenHeight * 0.08 : screenHeight * 0.05,
    },
    datePickerContainer: {
        alignItems: "center",
        marginVertical: screenHeight * 0.012,
    },
    datePickerButton: {
        width: "88%",
        backgroundColor: "#FFD700",
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 8,
        shadowColor: "transparent",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
        alignItems: "center",
        alignSelf: "center",
        marginTop: screenHeight * 0.025,
        marginBottom: 0,
    },
    datePickerText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#000",
        fontWeight: "bold",
    },
    loadingOverlay: {
        position: 'absolute',
        top: screenHeight * 0.15,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        justifyContent: 'flex-start',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingContainer: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 15,
        alignItems: 'center',
        minWidth: 200,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth: 2,
        borderColor: '#3B82F6',
    },
    loadingText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 10,
    },
});
