import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "white",
    },
    topSection: {
        flex: 0.8,
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        paddingTop: screenHeight * 0.012,
    },
    logo: {
        width: Math.min(screenWidth * 0.4, 150),
        height: Math.min(screenWidth * 0.4, 150),
        resizeMode: "contain",
        marginTop: screenHeight * 0.04,
    },
    textGradient: {
        marginTop: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.025,
        borderRadius: 5,
    },
    gradientText: {
        fontSize: screenWidth * 0.05,
        fontWeight: "bold",
        textAlign: "center",
        color: "white",
    },
    rowImagesContainer: {
        marginTop: screenHeight * 0.09,
        alignItems: "center",
    },
    imageRow1: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginTop: screenHeight * -0.035,
        paddingLeft: screenWidth * 0.05,
        gap: screenWidth * 0.08,
    },
    imageRow2: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginTop: screenHeight * 0.018,
        marginBottom: screenHeight * 0.05,
        paddingLeft: screenWidth * 0.05,
        gap: screenWidth * 0.08,
    },
    largeImage: {
        width: Math.min(screenWidth * 0.18, 70),
        height: Math.min(screenWidth * 0.18, 70),
        resizeMode: "contain",
        marginRight: screenWidth * 0.04,
    },
    bottomSection: {
        flex: 0.5,
        backgroundColor: "white",
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: screenWidth * 0.05,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
        marginTop: screenHeight * -0.025,
        alignItems: "center",
    },
    imagesContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: screenHeight * 0.025,
    },
    image: {
        width: Math.min(screenWidth * 0.2, 80),
        height: Math.min(screenWidth * 0.2, 80),
        resizeMode: "contain",
        marginHorizontal: screenWidth * 0.04,
    },
    title: {
        fontSize: screenWidth * 0.05,
        fontWeight: "bold",
        color: "black",
        marginBottom: screenHeight * 0.012,
        textAlign: "center",
    },
    description: {
        fontSize: screenWidth * 0.035,
        color: "gray",
        textAlign: "center",
        marginBottom: screenHeight * 0.025,
    },
    buttonCentered: {
        backgroundColor: "#FF5733",
        borderRadius: 8,
        paddingVertical: screenHeight * 0.018,
        paddingHorizontal: screenWidth * 0.05,
        width: "100%",
        alignItems: "center",
        marginBottom: screenHeight * 0.025,
    },
    buttonText: {
        color: "white",
        fontWeight: "bold",
        fontSize: screenWidth * 0.04,
        textAlign: "center",
    },
});
