import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    background: {
        flex: 1,
    },
    backButton: {
        position: "absolute",
        top: screenHeight * 0.09,
        left: screenWidth * 0.06,
        zIndex: 10,
    },
    backIcon: {
        fontSize: Math.min(screenWidth * 0.12, 48),
        color: "#000",
        fontWeight: "200",
    },
    header: {
        alignItems: "center",
        paddingVertical: screenHeight * 0.025,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginBottom: screenHeight * 0.025,
    },
    headerText: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: "bold",
        color: "#333",
    },
    searchContainer: {
        paddingHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
        marginTop: screenHeight * 0.065,
    },
    searchInput: {
        height: screenHeight * 0.065,
        backgroundColor: "#FFF",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        fontSize: Math.min(screenWidth * 0.04, 16),
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        color: "#333",
    },
    tabContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
    },
    tabButton: {
        flex: 1,
        marginHorizontal: screenWidth * 0.012,
        paddingVertical: screenHeight * 0.012,
        borderWidth: 2,
        borderColor: "#FFD700",
        borderRadius: 10,
        alignItems: "center",
    },
    tabButtonActive1: {
        backgroundColor: "#4CAF50",
    },
    tabButtonActive2: {
        backgroundColor: "#FF5733",
    },
    tabButtonText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#FFD700",
    },
    tabButtonTextActive: {
        color: "#FFF",
    },
    scrollableList: {
        flex: 1,
        marginHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
        borderRadius: 10,
        height: screenHeight * 0.5,
        overflow: "hidden",
    },
    personCard: {
        backgroundColor: "#FFF",
        borderRadius: 10,
        padding: screenWidth * 0.035,
        marginBottom: screenHeight * 0.018,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    personName: {
        fontSize: Math.min(screenWidth * 0.045, 18),
        fontWeight: "bold",
        color: "#333",
    },
    deleteButton: {
        backgroundColor: "#FF5733",
        paddingVertical: screenHeight * 0.006,
        paddingHorizontal: screenWidth * 0.04,
        borderRadius: 5,
        alignItems: "center",
        justifyContent: "center",
    },
    deleteButtonText: {
        color: "#FFF",
        fontSize: Math.min(screenWidth * 0.035, 14),
        fontWeight: "bold",
    },
    actionButtonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
    },
    publishButton: {
        flex: 1,
        backgroundColor: "#4CAF50",
        paddingVertical: screenHeight * 0.02,
        borderRadius: 10,
        marginHorizontal: screenWidth * 0.012,
        alignItems: "center",
    },
    publishButtonText: {
        color: "#FFF",
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
    },
    unpublishButton: {
        flex: 1,
        backgroundColor: "#FF5733",
        paddingVertical: screenHeight * 0.02,
        borderRadius: 10,
        marginHorizontal: screenWidth * 0.012,
        alignItems: "center",
    },
    unpublishButtonText: {
        color: "#FFF",
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    loadingText: {
        fontSize: Math.min(screenWidth * 0.045, 18),
        fontWeight: "bold",
        color: "#FFD700",
        marginTop: screenHeight * 0.012,
    },
    counterContainer: {
        alignItems: "center",
        marginTop: 0,
        paddingVertical: screenHeight * 0.012,
        backgroundColor: "#FFF",
        borderRadius: 10,
        marginHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    counterText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#333",
    },
});