import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: screenWidth * 0.06,
        paddingVertical: screenHeight * 0.02,
        backgroundColor: "#fff",
        alignItems: "stretch",
    },
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 1,
        alignItems: "center",
        paddingVertical: screenHeight * 0.025,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    headerText: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: "bold",
        color: "#333",
    },
    backButton: {
        position: "absolute",
        top: screenHeight * 0.09,
        left: screenWidth * 0.06,
        zIndex: 10,
    },
    backButtonText: {
        fontSize: Math.min(screenWidth * 0.12, 48),
        color: "#000",
        fontWeight: "200",
    },
    graphsContainer: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: screenHeight * 0.16,
        marginVertical: screenHeight * 0.025,
        width: "100%",
    },
    circularGraphContainer: {
        alignItems: "center",
        justifyContent: "center",
    },
    circularGraphText: {
        position: "absolute",
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        color: "#333",
    },
    circularGraphLabel: {
        marginTop: screenHeight * 0.006,
        fontSize: Math.min(screenWidth * 0.03, 12),
        color: "#333",
        fontWeight: "bold",
    },
    infoContainer: {
        width: "100%",
        marginTop: screenHeight * 0.037,
        paddingHorizontal: screenWidth * 0.04,
    },
    label: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
        marginBottom: screenHeight * 0.006,
        color: "#333",
        textAlign: "left",
        width: "100%",
    },
    input: {
        width: "100%",
        maxWidth: "100%",
        height: screenHeight * 0.055,
        borderColor: "#ccc",
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: screenWidth * 0.03,
        marginBottom: screenHeight * 0.018,
        backgroundColor: "#FFF",
        fontSize: Math.min(screenWidth * 0.035, 14),
        alignSelf: "stretch",
    },
    badgesContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginBottom: screenHeight * 0.025,
        justifyContent: "flex-start",
        width: "100%",
    },
    badge: {
        backgroundColor: "#1E90FF",
        color: "#FFF",
        paddingHorizontal: screenWidth * 0.025,
        paddingVertical: screenHeight * 0.006,
        borderRadius: 15,
        marginRight: screenWidth * 0.025,
        marginBottom: screenHeight * 0.012,
        fontSize: Math.min(screenWidth * 0.03, 12),
    },
    resetPasswordButton: {
        backgroundColor: "#FF4500",
        paddingVertical: screenHeight * 0.012,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 0,
    },
    resetPasswordText: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: Math.min(screenWidth * 0.035, 14),
    },
    scrollViewContent: {
        alignItems: "center",
        paddingBottom: screenHeight * 0.025,
        paddingHorizontal: screenWidth * 0.04,
    },
    participationCountContainer: {
        alignItems: "center",
        marginTop: screenHeight * 0.018,
        width: "100%",
        paddingHorizontal: screenWidth * 0.06,
    },
    participationCountText: {
        fontSize: Math.min(screenWidth * 0.05, 20),
        fontWeight: "bold",
        color: "#1E90FF",
        textShadowColor: "rgba(0, 0, 0, 0.3)",
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    modalBackground: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        width: "80%",
        backgroundColor: "#FFF",
        padding: screenWidth * 0.05,
        borderRadius: 10,
        alignItems: "center",
        elevation: 5,
    },
    modalTitle: {
        fontSize: Math.min(screenWidth * 0.05, 20),
        fontWeight: "bold",
        marginBottom: screenHeight * 0.012,
        color: "#333",
    },
    modalInput: {
        width: "100%",
        height: screenHeight * 0.055,
        borderColor: "#ccc",
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: screenWidth * 0.03,
        marginBottom: screenHeight * 0.018,
        backgroundColor: "#FFF",
        fontSize: Math.min(screenWidth * 0.035, 14),
    },
    modalButton: {
        backgroundColor: "#FFD700",
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 8,
        marginTop: screenHeight * 0.012,
    },
    resetButton: {
        backgroundColor: "#32CD32",
        paddingVertical: screenHeight * 0.015,
        borderRadius: 8,
        alignItems: "center",
        width: "48%",
    },
    closeButton: {
        backgroundColor: "#FF4500",
        paddingVertical: screenHeight * 0.015,
        borderRadius: 8,
        alignItems: "center",
        width: "48%",
    },
    modalButtonText: {
        color: "#333",
        fontWeight: "bold",
        fontSize: Math.min(screenWidth * 0.035, 14),
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: screenHeight * 0.025,
        width: "100%",
    },
    buttonText: {
        color: "#fff",
        fontSize: Math.min(screenWidth * 0.04, 16),
        fontWeight: "bold",
    },
    loadingOverlay: {
        position: 'absolute',
        top: screenHeight * 0.4,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        justifyContent: 'flex-start',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingContainer: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 15,
        alignItems: 'center',
        minWidth: 200,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth: 2,
        borderColor: '#3B82F6',
    },
    loadingText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 10,
    },
});