import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    background: {
        flex: 1,
    },
    backButton: {
        position: "absolute",
        top: screenHeight * 0.09,
        left: screenWidth * 0.06,
        zIndex: 10,
    },
    backIcon: {
        fontSize: Math.min(screenWidth * 0.12, 48),
        color: "#000",
        fontWeight: "200",
    },
    header: {
        alignItems: "center",
        paddingVertical: screenHeight * 0.025,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginBottom: screenHeight * 0.012,
    },
    headerText: {
        fontSize: Math.min(screenWidth * 0.06, 24),
        fontWeight: "bold",
        color: "#333",
    },
    searchContainer: {
        paddingHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.012,
        marginTop: screenHeight * 0.025,
    },
    searchInput: {
        height: screenHeight * 0.065,
        backgroundColor: "#FFF",
        borderRadius: 10,
        paddingHorizontal: screenWidth * 0.04,
        fontSize: Math.min(screenWidth * 0.04, 16),
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        color: "#333",
    },
    scrollableList: {
        paddingBottom: screenHeight * 0.025,
    },
    eventCard: {
        backgroundColor: "#FFF",
        borderRadius: 10,
        padding: screenWidth * 0.04,
        marginBottom: screenHeight * 0.018,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        flexDirection: "column",
        alignItems: "center",
        marginHorizontal: screenWidth * 0.05,
    },
    eventDetails: {
        flex: 1,
        alignItems: "center",
    },
    eventName: {
        fontSize: Math.min(screenWidth * 0.045, 18),
        fontWeight: "bold",
        color: "#333",
        marginBottom: screenHeight * 0.006,
    },
    eventDate: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#690",
        fontWeight: "bold",
        marginBottom: screenHeight * 0.006,
    },
    eventTime: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#690",
        fontWeight: "bold",
        marginBottom: screenHeight * 0.006,
    },
    eventQuota: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#444",
        fontWeight: "bold",
        marginBottom: screenHeight * 0.012,
    },
    eventPoint: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#08d3d3",
        fontWeight: "bold",
        marginBottom: screenHeight * 0.018,
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        paddingHorizontal: screenWidth * 0.05,
    },
    applyButton: {
        backgroundColor: "#4CAF50",
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 5,
    },
    cancelButton: {
        backgroundColor: "#D32F2F",
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 5,
    },
    buttonText: {
        fontSize: Math.min(screenWidth * 0.035, 14),
        color: "#FFF",
        fontWeight: "bold",
    },
    warningContainer: {
        padding: screenWidth * 0.04,
        backgroundColor: "rgba(255, 0, 0, 0.1)",
        borderRadius: 10,
        marginHorizontal: screenWidth * 0.05,
        marginBottom: screenHeight * 0.025,
    },
    warningText: {
        color: "#D32F2F",
        fontSize: Math.min(screenWidth * 0.035, 14),
        textAlign: "center",
        fontWeight: "bold",
    },
    datePickerContainer: {
        alignItems: "center",
        marginVertical: screenHeight * 0.012,
    },
    datePickerButton: {
        width: "88%",
        backgroundColor: "#FFD700",
        paddingVertical: screenHeight * 0.012,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 8,
        shadowColor: "transparent",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
        alignItems: "center",
        alignSelf: "center",
        marginTop: screenHeight * 0.075,
        marginBottom: 0,
    },
    datePickerText: {
        fontSize: Math.min(screenWidth * 0.04, 16),
        color: "#000",
        fontWeight: "bold",
    },
    loadingOverlay: {
        position: 'absolute',
        top: screenHeight * 0.4,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
        justifyContent: 'flex-start',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingContainer: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 15,
        alignItems: 'center',
        minWidth: 200,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth: 2,
        borderColor: '#3B82F6',
    },
    loadingText: {
        color: '#3B82F6',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 10,
    },
});